// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:fd44d886-8d10-4778-a4f8-d988a47a7df4",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_pbrkuQoQ8",
    "aws_user_pools_web_client_id": "78gamntf4b2oqd66rk42q6kui0",
    "aws_user_files_s3_bucket": "amplify-nicki-demo",
    "aws_user_files_s3_bucket_region": "us-west-2",
    "aws_content_delivery_bucket": "amplify-nicki-demo-hosting",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://amplify-nicki-demo-hosting.s3-website-us-west-2.amazonaws.com"
};


export default awsmobile;
